'use strict';
const KEY='psico-draft-v1', baseline=structuredClone(window.SITE_CONTENT);
let data=structuredClone(baseline),tab='inicio',page='index.html',dirty=false;
try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.version===1&&x.pages&&x.settings&&Array.isArray(x.articles))data=x;}catch{}
const workspace=document.getElementById('workspace'),status=document.getElementById('status');
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function changed(){dirty=true;status.textContent='Cambios pendientes de guardar. La web pública no cambia hasta publicar.';}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));dirty=false;status.textContent='Borrador guardado en este navegador · '+new Date().toLocaleTimeString('es-ES');return true}catch{status.textContent='No hay espacio para guardar el borrador. Descarga una copia desde Publicar antes de cerrar.';return false}}
function field(parent,label,obj,key,type='text'){const l=el('label',label),input=el(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;if(type==='checkbox')input.checked=!!obj[key];else input.value=obj[key]??'';input.addEventListener('input',()=>{obj[key]=type==='checkbox'?input.checked:input.value;changed()});l.append(input);parent.append(l);return input;}
function button(parent,text,fn,cls){const b=el('button',text,cls);b.type='button';b.onclick=fn;parent.append(b);return b;}
function card(title){const c=el('div',undefined,'card');if(title)c.append(el('h2',title));workspace.append(c);return c;}
function pageSelect(){const l=el('label','Página'),select=el('select');for(const key of Object.keys(data.pages)){const o=el('option',key==='index.html'?'Página principal':key);o.value=key;select.append(o)}select.value=page;select.onchange=()=>{page=select.value;render()};l.append(select);workspace.append(l);}
async function imageUpload(file){if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw Error('Elige una imagen JPG, PNG o WebP.');if(file.size>15*1024*1024)throw Error('La imagen supera 15 MB.');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1600/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/webp',.82)}finally{URL.revokeObjectURL(url)}}
function imageFields(c,obj,src='src',alt='alt'){const img=el('img',undefined,'photo');img.src=obj[src]||'';img.alt=obj[alt]||'';c.append(img);const input=field(c,'Dirección de la imagen o ruta del archivo',obj,src);input.addEventListener('change',()=>{img.src=obj[src]});field(c,'Descripción de la imagen (accesibilidad)',obj,alt);const label=el('label','O sube una foto desde tu dispositivo'),f=el('input');f.type='file';f.accept='image/jpeg,image/png,image/webp';f.onchange=async()=>{if(!f.files[0])return;try{obj[src]=await imageUpload(f.files[0]);img.src=obj[src];input.value=obj[src];changed();status.textContent='Foto optimizada y añadida al borrador. Guarda para conservarla.'}catch(e){status.textContent=e.message}};label.append(f);c.append(label);}
function download(filename,body,type){const u=URL.createObjectURL(new Blob([body],{type}));const a=el('a');a.href=u;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000)}
function validate(x){if(!x||x.version!==1||!x.settings||!x.pages||!Array.isArray(x.articles))throw Error('La copia no tiene el formato esperado.');for(const [key,p] of Object.entries(baseline.pages)){if(!x.pages[key])throw Error('Falta una página en la copia.');for(const k of Object.keys(p.texts))if(typeof x.pages[key].texts?.[k]?.value!=='string')throw Error('La copia no es compatible con esta versión.')}if(x.articles.some(a=>typeof a.title!=='string'||typeof a.body!=='string'))throw Error('Hay artículos no válidos.');return x}
function render(){workspace.replaceChildren();const names={inicio:'Tu consulta',textos:'Textos y páginas',fotos:'Fotografías',articulos:'Artículos',enlaces:'Enlaces',publicar:'Publicar los cambios'};document.getElementById('heading').textContent=names[tab];document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
if(tab==='inicio'){
 workspace.append(el('p','Personaliza tu web sin tocar código. Empieza por tus datos, revisa los textos y abre la vista previa.','notice'));
 let c=card('Identidad y contacto');const g=el('div',undefined,'grid');c.append(g);field(g,'Nombre de la profesional',data.settings,'name');field(g,'Ciudad',data.settings,'city');field(g,'WhatsApp con prefijo, por ejemplo 34600111222',data.settings,'phone','tel');field(g,'Correo profesional',data.settings,'email','email');field(c,'Agenda externa (URL HTTPS de Calendly, Doctoralia u otra)',data.settings,'bookingUrl','url');field(c,'Color principal',data.settings,'accent','color');
 c=card('Título y descripción');field(c,'Título de la página',data.settings,'title');field(c,'Descripción para buscadores y redes',data.settings,'description','textarea');c.append(el('p','Nombre y ciudad sustituyen automáticamente [NOMBRE] y [CIUDAD]. Los demás datos, tarifas y credenciales se editan en Textos y páginas.','muted'));
}
if(tab==='textos'){
 pageSelect();const filter=el('div',undefined,'filter'),search=el('input'),select=el('select');search.placeholder='Buscar texto, precio o campo pendiente…';search.setAttribute('aria-label','Buscar textos');const groups=[...new Set(Object.values(data.pages[page].texts).map(t=>t.group))];for(const v of ['Todas las secciones',...groups]){const o=el('option',v);o.value=v;select.append(o)}select.setAttribute('aria-label','Sección');filter.append(search,select);workspace.append(filter);const list=el('div');workspace.append(list);function show(){list.replaceChildren();let count=0;for(const [id,t]of Object.entries(data.pages[page].texts)){if(select.selectedIndex>0&&t.group!==select.value)continue;if(search.value&&!t.value.toLowerCase().includes(search.value.toLowerCase()))continue;const c=el('div',undefined,'card');field(c,t.group+' · '+id,t,'value',t.value.length>90?'textarea':'text');list.append(c);count++}if(!count)list.append(el('p','No hay textos que coincidan.'))}search.oninput=show;select.onchange=show;show();
}
if(tab==='fotos'){pageSelect();workspace.append(el('p','Las fotos subidas se reducen a un máximo de 1600 píxeles y se incluyen en el archivo de contenido. Usa fotos propias o con permiso.','notice'));const entries=Object.entries(data.pages[page].images);if(!entries.length)card('Esta página no contiene fotografías.');for(const[id,obj]of entries){const c=card(obj.alt||id);imageFields(c,obj)}}
if(tab==='enlaces'){pageSelect();for(const[id,obj]of Object.entries(data.pages[page].links)){if(obj.href.includes('wa.me'))continue;const c=card(obj.label||id);field(c,'Destino del enlace',obj,'href');}workspace.append(el('p','El WhatsApp se configura en Tu consulta. Los enlaces internos del menú conservan sus secciones.','muted'))}
if(tab==='articulos'){
 button(workspace,'+ Crear artículo',()=>{data.articles.unshift({id:crypto.randomUUID(),title:'Nuevo artículo',excerpt:'',body:'',image:'',imageAlt:'',published:false});changed();render()},'primary');
 if(!data.articles.length)card('Todavía no hay artículos. Crea el primero cuando lo tengas listo.');
 data.articles.forEach((a,i)=>{const c=card('Artículo '+(i+1));field(c,'Título',a,'title');field(c,'Resumen',a,'excerpt','textarea');field(c,'Contenido (texto con saltos de párrafo)',a,'body','textarea');const det=el('details');det.append(el('summary','Foto del artículo'));imageFields(det,a,'image','imageAlt');c.append(det);field(c,'Visible en la web después de publicar',a,'published','checkbox');const actions=el('div',undefined,'actions');c.append(actions);if(i>0)button(actions,'↑ Subir',()=>{[data.articles[i-1],data.articles[i]]=[data.articles[i],data.articles[i-1]];changed();render()});button(actions,'Eliminar artículo',()=>{if(confirm('¿Eliminar este artículo del borrador?')){data.articles.splice(i,1);changed();render()}},'danger')});
}
if(tab==='publicar'){
 const c=card('Del borrador a tu web');c.append(el('p','Guardar aquí no modifica GitHub. Para que todos vean los cambios, descarga el contenido y súbelo a tu repositorio.','notice'));
 for(const text of ['1. Guarda y revisa el borrador con Vista previa.','2. Descarga content.js con el botón de abajo.','3. En GitHub abre Psicologi → Code → + → Upload files.','4. Arrastra content.js a la carpeta principal y pulsa Commit changes.','5. Espera a que termine la publicación y recarga tu web.'])c.append(el('p',text,'step'));
 button(c,'Descargar content.js para publicar',()=>{download('content.js','window.SITE_CONTENT = '+JSON.stringify(data,null,2)+';\n','text/javascript');status.textContent='Archivo descargado. Súbelo a GitHub para publicar.'},'primary');
 const b=card('Copia de seguridad');button(b,'Descargar copia JSON',()=>download('copia-consulta.json',JSON.stringify(data,null,2),'application/json'));const l=el('label','Restaurar una copia JSON'),f=el('input');f.type='file';f.accept='.json,application/json';f.onchange=async()=>{if(!f.files[0])return;try{const x=validate(JSON.parse(await f.files[0].text()));if(confirm('¿Reemplazar el borrador con esta copia?')){data=x;changed();save();render()}}catch(e){status.textContent='No se pudo importar: '+e.message}};l.append(f);b.append(l);button(b,'Descartar borrador y cargar lo publicado',()=>{if(confirm('¿Descartar todos los cambios locales y volver al contenido publicado?')){data=structuredClone(baseline);localStorage.removeItem(KEY);dirty=false;render();status.textContent='Contenido publicado cargado.'}},'danger');
 const warning=card('Antes de publicar');let n=0;for(const p of Object.values(data.pages))for(const t of Object.values(p.texts)){let v=t.value;if(data.settings.name)v=v.replaceAll('[NOMBRE]',data.settings.name);if(data.settings.city)v=v.replaceAll('[CIUDAD]',data.settings.city);if(/\[[^\]]+\]/.test(v))n++}warning.append(el('p',n+' textos contienen campos entre corchetes pendientes de revisar.'));warning.append(el('p','Este editor no es un área privada ni almacena pacientes. Cualquier visitante puede abrirlo y editar una copia en su propio navegador; publicar exige acceso a tu cuenta de GitHub.','muted'));
}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});document.getElementById('save').onclick=save;document.getElementById('preview').onclick=()=>{if(save())window.open((tab==='textos'||tab==='fotos'||tab==='enlaces'?page:'index.html')+'?preview=1','_blank','noopener')};window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});render();
